version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "https://wxdfjvndeuxatarenovg.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZGZqdm5kZXV4YXRhcmVub3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM5ODk4MTAsImV4cCI6MjAzOTU2NTgxMH0.10IPQx5CPFzKpQPE6dkwlC8SCmJt-WOiysKY2I_n8go"
